# Generated by Django 5.1.5 on 2025-04-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0041_companyincharge_is_online_consultant_is_online_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_user',
            name='confirm_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='new_user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', max_length=10),
        ),
    ]
