# Generated by Django 5.1.5 on 2025-04-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0042_new_user_confirm_password_new_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyincharge',
            name='confirm_password',
            field=models.CharField(default='null', max_length=128),
        ),
        migrations.AddField(
            model_name='companyincharge',
            name='designation',
            field=models.CharField(default='Null', max_length=100),
        ),
    ]
