# Generated by Django 5.1.5 on 2025-04-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0044_consultant_confirm_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='designation',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='universityincharge',
            name='confirm_password',
            field=models.CharField(default='null', max_length=128),
        ),
    ]
