# Generated by Django 5.1.5 on 2025-04-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0045_consultant_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
