# Generated by Django 5.1.5 on 2025-04-21 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0046_answer_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='likes',
        ),
    ]
