# Generated by Django 5.1.5 on 2025-04-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0047_remove_answer_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='confirm_password',
            field=models.CharField(default='null', max_length=128),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='designation',
            field=models.CharField(default='Null', max_length=100),
        ),
    ]
