# Generated by Django 5.1.5 on 2025-04-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0048_jobseeker_confirm_password_jobseeker_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='linkedin_profile',
            field=models.URLField(blank=True, null=True),
        ),
    ]
